### ISSUE TITLE
webkitfltk build failed on fedora 23 (x86-64)

### ISSUE THREAD

**Issue by kuh3h3** [clbr/webkitfltk#12]
checked out trunk and tried to compile. but error occurred at almost last testapp build.

g++ -o testapp/testapp testapp/_.cpp -I .. -I ../.. -I . -I ../../WTF -I webkit -I WebCoreSupport -I ../Storage -std=gnu++11 -g -Wall -DBUILDING_FLTK__ -D_GLIBCXX_USE_SCHED_YIELD -D_GLIBCXX_USE_NANOSLEEP -I/usr/include  -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/libxml2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I ../../JavaScriptCore/ForwardingHeaders -I ../../WebCore -I ../../WebCore/ForwardingHeaders -I ../../WebCore/Modules/geolocation -I ../../WebCore/Modules/filesystem -I ../../WebCore/Modules/mediastream -I ../../WebCore/Modules/navigatorcontentutils -I ../../WebCore/Modules/networkinfo -I ../../WebCore/Modules/webdatabase -I ../../WebCore/Modules/websockets -I ../../WebCore/accessibility -I ../../WebCore/bindings/generic -I ../../WebCore/bindings/js -I ../../WebCore/bindings -I ../../WebCore/bridge -I ../../WebCore/bridge/c -I ../../WebCore/bridge/jsc -I ../../WebCore/css -I ../../WebCore/dom -I ../../WebCore/dom/default -I ../../WebCore/editing -I ../../WebCore/fileapi -I ../../WebCore/history -I ../../WebCore/html -I ../../WebCore/html/forms -I ../../WebCore/html/shadow -I ../../WebCore/html/track -I ../../WebCore/inspector -I ../../WebCore/loader -I ../../WebCore/loader/archive -I ../../WebCore/loader/appcache -I ../../WebCore/loader/icon -I ../../WebCore/loader/cache -I ../../WebCore/page -I ../../WebCore/page/animation -I ../../WebCore/page/scrolling -I ../../WebCore/platform -I ../../WebCore/platform/animation -I ../../WebCore/platform/audio -I ../../WebCore/platform/fltk -I ../../WebCore/platform/cairo -I ../../WebCore/platform/graphics -I ../../WebCore/platform/graphics/filters -I ../../WebCore/platform/graphics/harfbuzz -I ../../WebCore/platform/graphics/harfbuzz/ng -I ../../WebCore/platform/graphics/cairo -I ../../WebCore/platform/graphics/texmap -I ../../WebCore/platform/graphics/opentype -I ../../WebCore/platform/graphics/transforms -I ../../WebCore/platform/mediastream -I ../../WebCore/platform/mock -I ../../WebCore/platform/network -I ../../WebCore/platform/network/curl -I ../../WebCore/platform/sql -I ../../WebCore/platform/text -I ../../WebCore/plugins -I ../../WebCore/rendering -I ../../WebCore/rendering/line -I ../../WebCore/rendering/shapes -I ../../WebCore/rendering/style -I ../../WebCore/storage -I ../../WebCore/style -I ../../WebCore/svg -I ../../WebCore/svg/animation -I ../../WebCore/svg/graphics -I ../../WebCore/svg/properties -I ../../WebCore/workers -I ../../JavaScriptCore -I ../../JavaScriptCore/API -I ../../JavaScriptCore/assembler -I ../../JavaScriptCore/bytecode -I ../../JavaScriptCore/bytecompiler -I ../../JavaScriptCore/disassembler -I ../../JavaScriptCore/dfg -I ../../JavaScriptCore/heap -I ../../JavaScriptCore/debugger -I ../../JavaScriptCore/interpreter -I ../../JavaScriptCore/jit -I ../../JavaScriptCore/llint -I ../../JavaScriptCore/parser -I ../../JavaScriptCore/profiler -I ../../JavaScriptCore/runtime  -DENABLE_CANVAS_PATH  -DENABLE_CHANNEL_MESSAGING  -DENABLE_CONTEXT_MENUS  -DENABLE_CSS_BOX_DECORATION_BREAK  -DENABLE_CSS_TRANSFORMS_ANIMATIONS_UNPREFIXED  -DENABLE_DETAILS_ELEMENT  -DENABLE_FTPDIR  -DENABLE_HIDDEN_PAGE_DOM_TIMER_THROTTLING  -DENABLE_ICONDATABASE  -DENABLE_IMAGE_DECODER_DOWN_SAMPLING  -DENABLE_JIT  -DENABLE_LEGACY_VENDOR_PREFIXES  -DENABLE_LINK_PREFETCH  -DENABLE_LLINT  -DENABLE_METER_ELEMENT  -DENABLE_NAVIGATOR_HWCONCURRENCY  -DENABLE_PROMISES  -DENABLE_PROGRESS_ELEMENT  -DENABLE_SVG_FONTS  -DENABLE_TEMPLATE_ELEMENT  -DENABLE_WEB_SOCKETS  -DENABLE_XSLT  -DENABLE_VIEW_MODE_CSS_MEDIA  -DENABLE_CURSOR_SUPPORT  -DENABLE_DRAG_SUPPORT  -DENABLE_FIFTH_VIDEO  -DENABLE_VIDEO  -DENABLE_VIDEO_TRACK  -DENABLE_MATHML  -DENABLE_TEXT_CARET  -DENABLE_TEXT_SELECTION  -DENABLE_WILL_REVEAL_EDGE_EVENTS  -DUSE_TEXTURE_MAPPER  -DENABLE_REQUEST_AUTOCOMPLETE  -DUSE_CROSS_PLATFORM_CONTEXT_MENUS -DENABLE_NETSCAPE_PLUGIN_API=0 -DENABLE_DATE_AND_TIME_INPUT_TYPES=0 -ffunction-sections -fdata-sections -fno-rtti -fno-exceptions -Wall -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -fvisibility-inlines-hidden -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT /tmp/libwebkitfltk.a \
    -lz -pthread -lxslt -lxml2 -ldl -lsqlite3 `icu-config --ldflags` -lharfbuzz -lharfbuzz-icu -lfreetype -lfontconfig -lcairo -lpng -ljpeg -lrt -lcurl -lssl -lcrypto -lglib-2.0 `/bin/fltk-config --ldflags --use-images` -static-libgcc -static-libstdc++
/tmp/libwebkitfltk.a(FrameSelection.o): In function `WebCore::FrameSelection::modify(WebCore::FrameSelection::EAlteration, WebCore::SelectionDirection, WebCore::TextGranularity, WebCore::EUserTriggered)':
FrameSelection.cpp:(.text._ZN7WebCore14FrameSelection6modifyENS0_11EAlterationENS_18SelectionDirectionENS_15TextGranularityENS_14EUserTriggeredE+0x610): undefined reference to`WebCore::AXObjectCache::setTextSelectionIntent(WebCore::AXTextStateChangeIntent const&)'
/tmp/libwebkitfltk.a(AccessibilityObject.o): In function `WebCore::AccessibilityObject::updateChildrenIfNecessary()':
AccessibilityObject.cpp:(.text._ZN7WebCore19AccessibilityObject25updateChildrenIfNecessaryEv+0x53): undefined reference to`WebCore::AXAttributeCacheEnabler::AXAttributeCacheEnabler(WebCore::AXObjectCache_)'
AccessibilityObject.cpp:(.text._ZN7WebCore19AccessibilityObject25updateChildrenIfNecessaryEv+0x78): undefined reference to `WebCore::AXAttributeCacheEnabler::~AXAttributeCacheEnabler()'
/tmp/libwebkitfltk.a(AccessibilityRenderObject.o): In function`WebCore::setTextSelectionIntent(WebCore::AccessibilityRenderObject const&, WebCore::AXTextStateChangeType)':
AccessibilityRenderObject.cpp:(.text._ZN7WebCoreL22setTextSelectionIntentERKNS_25AccessibilityRenderObjectENS_21AXTextStateChangeTypeE+0x70): undefined reference to `WebCore::AXObjectCache::setTextSelectionIntent(WebCore::AXTextStateChangeIntent const&)'
AccessibilityRenderObject.cpp:(.text._ZN7WebCoreL22setTextSelectionIntentERKNS_25AccessibilityRenderObjectENS_21AXTextStateChangeTypeE+0x81): undefined reference to`WebCore::AXObjectCache::setIsSynchronizingSelection(bool)'
collect2: error: ld returned 1 exit status
Makefile:134: recipe for target 'testapp/testapp' failed
make: **\* [testapp/testapp] Error 1
make: Leaving directory '/run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/webkitfltk/Source/WebKit/fltk'

**Comment by kuh3h3** [comment]
even if build and install without test app, 
fifth also says same error in configure check.

checking for webkitInit in -lwebkitfltk... no
configure: error: libwebkitfltk not found

# 

configure:5958: checking for webkitInit in -lwebkitfltk
configure:5983: g++ -o conftest -g -O2 -pthread -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/freetype2 -isystem /usr/include/libdrm -isystem /usr/include/libpng16 -isystem /usr/include/freetype2 -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/freetype2 -isystem /usr/include/libdrm -isystem /usr/include/libpng16 -fvisibility-inlines-hidden -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT   conftest.cpp -lwebkitfltk  -lphysfs -ljpeg -lz -lrt -ldl -lurlmatch   -L/usr/lib64 -Wl,-rpath,/usr/lib64 -lfltk_images -lpng -lz -ljpeg -lfltk -lXrender -lXcursor -lXfixes -lXext -lXft -lfontconfig -lXinerama -lpthread -ldl -lm -lX11 -lharfbuzz-icu -lharfbuzz -licui18n -licuuc -licudata -lwebkitfltk  -lxslt -lxml2 -lz -lm -ldl -lm -lxml2 -lsqlite3 -lfontconfig -lfreetype -lcairo -lpng16 -lcurl -lssl -lcrypto -lglib-2.0  >&5
/usr/lib64/libwebkitfltk.a(FrameSelection.o): In function `WebCore::FrameSelection::modify(WebCore::FrameSelection::EAlteration, WebCore::SelectionDirection, WebCore::TextGranularity, WebCore::EUserTriggered)':
FrameSelection.cpp:(.text._ZN7WebCore14FrameSelection6modifyENS0_11EAlterationENS_18SelectionDirectionENS_15TextGranularityENS_14EUserTriggeredE+0x610): undefined reference to`WebCore::AXObjectCache::setTextSelectionIntent(WebCore::AXTextStateChangeIntent const&)'
/usr/lib64/libwebkitfltk.a(AccessibilityObject.o): In function `WebCore::AccessibilityObject::updateChildrenIfNecessary()':
AccessibilityObject.cpp:(.text._ZN7WebCore19AccessibilityObject25updateChildrenIfNecessaryEv+0x53): undefined reference to`WebCore::AXAttributeCacheEnabler::AXAttributeCacheEnabler(WebCore::AXObjectCache_)'
AccessibilityObject.cpp:(.text._ZN7WebCore19AccessibilityObject25updateChildrenIfNecessaryEv+0x78): undefined reference to `WebCore::AXAttributeCacheEnabler::~AXAttributeCacheEnabler()'
/usr/lib64/libwebkitfltk.a(AccessibilityRenderObject.o): In function`WebCore::setTextSelectionIntent(WebCore::AccessibilityRenderObject const&, WebCore::AXTextStateChangeType)':
AccessibilityRenderObject.cpp:(.text._ZN7WebCoreL22setTextSelectionIntentERKNS_25AccessibilityRenderObjectENS_21AXTextStateChangeTypeE+0x70): undefined reference to `WebCore::AXObjectCache::setTextSelectionIntent(WebCore::AXTextStateChangeIntent const&)'
AccessibilityRenderObject.cpp:(.text._ZN7WebCoreL22setTextSelectionIntentERKNS_25AccessibilityRenderObjectENS_21AXTextStateChangeTypeE+0x81): undefined reference to`WebCore::AXObjectCache::setIsSynchronizingSelection(bool)'
collect2: error: ld returned 1 exit status
configure:5983: $? = 1
configure: failed program was:
| /_ confdefs.h _/
| #define PACKAGE_NAME "Fifth"
| #define PACKAGE_TARNAME "fifth"
| #define PACKAGE_VERSION "0.5"
| #define PACKAGE_STRING "Fifth 0.5"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "fifth"
| #define VERSION "0.5"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define **EXTENSIONS** 1
| #define _ALL_SOURCE 1
| #define _GNU_SOURCE 1
| #define _POSIX_PTHREAD_SEMANTICS 1
| #define _TANDEM_SOURCE 1
| #define HAVE_PTHREAD_PRIO_INHERIT 1
| #define HAVE_PTHREAD 1
| #define HAVE_LIBURLMATCH 1
| #define HAVE_LIBDL 1
| #define HAVE_LIBRT 1
| #define HAVE_LIBZ 1
| #define HAVE_LIBJPEG 1
| #define HAVE_LIBPHYSFS 1
| /_ end confdefs.h.  _/
| 
| /_ Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char webkitInit ();
| int
| main ()
| {
| return webkitInit ();
|   ;
|   return 0;
| }
configure:5992: result: no
configure:6002: error: libwebkitfltk not found

**Comment by clbr** [comment]
I confirm those symbols are missing in my build as well, but they do
not break the build for some reason. It's missing #ifs in a couple
places, and likely has upstream fixes I can backport. Will check later.

**Comment by clbr** [comment]
Please try current git.

**Comment by kuh3h3** [comment]
tried current. build ok. fifth build also ok.
but if run fifth, open https://youtube.com,
this error occurred not like official binary version.

https://www.youtube.com/: error 59,Couldn`t use specified SSL cipher.

if use official binary, request ilovebieber.

**Comment by kuh3h3** [comment]
open gmail,gdrive ok , but can not open  youtube in fifth private build

**Comment by clbr** [comment]
That would point to something being wrong in your OpenSSL library - the
prebuilt binary comes with its own OpenSSL.

**Comment by kuh3h3** [comment]
If remove bundled binary lib and copy & use system ssl libry 
[reandr@kuh3h3 fifth-0.5] $ rm libcrypto.so.1.0.0 libssl.so.1.0.0
[reandr@kuh3h3 fifth-0.5] $ cp /usr/lib64/libcrypto.so.10 libcrypto.so.1.0.0
[reandr@kuh3h3 fifth-0.5] $ cp /usr/lib64/libssl.so.10 libssl.so.1.0.0

fifth still loads well youtube ,and requests ilovebieber

Rather problem was at libcurl.so.4
[reandr@kuh3h3 fifth-0.5] $ rm libcurl.so.4
[reandr@kuh3h3 fifth-0.5] $ cp /usr/lib64/libcurl.so.4 libcurl.so.4

fifth failed to load youtube,

Is ther any special compile flags in bundled libcurl.so.4?

**Comment by clbr** [comment]
No, no special flags. It might be the opposite, your distro's curl has some flags that affect SSL options.

$ curl --version
curl 7.45.0

$ curl-config --configure
 '--enable-threaded-resolver' '--without-librtmp' '--prefix=/usr' 'CFLAGS=-O3 -march=nocona -mtune=k8 -pipe -fomit-frame-pointer' 'LDFLAGS=-Wl,-O1'

**Comment by kuh3h3** [comment]
so weird. my curl is fedora 23 default.

[reandr@kuh3h3 ~] $ curl --version
curl 7.43.0 (x86_64-redhat-linux-gnu) libcurl/7.43.0 NSS/3.22 Basic ECC zlib/1.2.8 libidn/1.32 libssh2/1.6.0 nghttp2/1.7.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets Metalink 
[reandr@kuh3h3 ~] $ curl-config --configure
 '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--disable-static' '--enable-symbol-hiding' '--enable-ipv6' '--enable-ldaps' '--enable-manual' '--enable-threaded-resolver' '--with-ca-bundle=/etc/pki/tls/certs/ca-bundle.crt' '--with-gssapi' '--with-libidn' '--with-libmetalink' '--with-libssh2' '--with-nghttp2' '--without-ssl' '--with-nss' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'

**Comment by clbr** [comment]
--without-ssl --with-nss

The webkit curl layer expects curl to be compiled with openssl. Your curl is built with NSS.

**Comment by kuh3h3** [comment]
thanks for kind reply.  i will rebuild curl with openssl.

**Comment by kuh3h3** [comment]
it works well. i`ll close this issue.

[reandr@kuh3h3 ~] $ curl --version
curl 7.49.0-DEV (x86_64-unknown-linux-gnu) libcurl/7.49.0-DEV OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 libpsl/0.7.0 (+libicu/54.1) libssh2/1.6.0 nghttp2/1.10.0-DEV librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets Metalink PSL 

[reandr@kuh3h3 ~] $ curl-config --configure
 '--prefix=/usr' '--enable-threaded-resolver' '--with-ssl' '--with-gssapi=/usr' '--with-libmetalink' '--with-nghttp2'
