### ISSUE TITLE
Problem compiling for RPi3

### ISSUE THREAD

**Issue by juanitotc** [clbr/webkitfltk#18]
make -C Source/WTF/wtf CXX="g++ -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -DNDEBUG"

..fails around line 310 in WTF/wtf/Platform.h, but works for -march=armv{6,7}.

If the test is removed, wtf seems to compile without error.

**Comment by clbr** [comment]
ARMv8 support will happen when a more recent upstream snapshot is pulled in.
