### ISSUE TITLE
RPi3 compile failure

### ISSUE THREAD

**Issue by juanitotc** [clbr/webkitfltk#19]
After resolving the problem in #18 

make -C Source/WebCore CXX="g++ -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -DNDEBUG"

fails with:

rendering/shapes/BoxShape.cpp: In function 'WebCore::LayoutUnit WebCore::adjustRadiusForMarginBoxShape(WebCore::LayoutUnit, WebCore::LayoutUnit)':
rendering/shapes/BoxShape.cpp:46:56: error: call of overloaded 'pow(WebCore::LayoutUnit, int)' is ambiguous
         return radius + (margin * (1 + pow(ratio - 1, 3)));
                                                        ^
where the ^ is under the first of the three )))

full code below:

`g++ -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -DNDEBUG -c -o rendering/shapes/BoxShape.o -I .. -I . -I ../WTF -std=gnu++11 -DBUILDING_FLTK__ -D_GLIBCXX_USE_SCHED_YIELD -D_GLIBCXX_USE_NANOSLEEP -D_REENTRANT  -DU_HAVE_ELF_H=1 -DU_HAVE_ATOMIC=1   -I/usr/local/include   -I Modules/battery -I Modules/airplay -I Modules/encryptedmedia -I Modules/gamepad -I Modules/gamepad/deprecated -I Modules/geolocation -I Modules/indexeddb -I Modules/indieui -I Modules/mediacontrols/ -I Modules/mediasource -I Modules/mediastream -I Modules/navigatorcontentutils -I Modules/notifications -I Modules/plugins -I Modules/proximity -I Modules/quota -I Modules/speech -I Modules/streams -I Modules/vibration -I Modules/webaudio -I Modules/webdatabase -I Modules/websockets -I accessibility -I bindings -I bindings/generic -I bindings/js -I bridge -I bridge/c -I bridge/jsc -I contentextensions -I crypto -I crypto/algorithms -I crypto/keys -I crypto/parameters -I css -I cssjit -I dom -I dom/default -I editing -I fileapi -I history -I html -I html/canvas -I html/forms -I html/parser -I html/shadow -I html/track -I inspector -I loader -I loader/appcache -I loader/archive -I loader/archive/mhtml -I loader/cache -I loader/icon -I mathml -I page -I page/animation -I page/scrolling -I platform -I platform/animation -I platform/audio -I platform/graphics -I platform/graphics/cpu/arm -I platform/graphics/cpu/arm/filters -I platform/graphics/filters -I platform/graphics/filters/texmap -I platform/graphics/harfbuzz -I platform/graphics/harfbuzz/ng -I platform/graphics/opentype -I platform/graphics/texmap -I platform/graphics/transforms -I platform/image-decoders -I platform/image-decoders/bmp -I platform/image-decoders/gif -I platform/image-decoders/ico -I platform/image-decoders/jpeg -I platform/image-decoders/png -I platform/image-decoders/webp -I platform/mediastream -I platform/mock -I platform/mock/mediasource -I platform/network -I platform/sql -I platform/text -I platform/text/icu -I plugins -I rendering -I rendering/line -I rendering/mathml -I rendering/shapes -I rendering/style -I rendering/svg -I replay -I storage -I style -I svg -I svg/animation -I svg/graphics -I svg/graphics/filters -I svg/properties -I websockets -I workers -I xml -I xml/parser -I ../JavaScriptCore -I ../JavaScriptCore/ForwardingHeaders -I ../JavaScriptCore/API -I ../JavaScriptCore/assembler -I ../JavaScriptCore/bytecode -I ../JavaScriptCore/bytecompiler -I ../JavaScriptCore/dfg -I ../JavaScriptCore/disassembler -I ../JavaScriptCore/heap -I ../JavaScriptCore/debugger -I ../JavaScriptCore/interpreter -I ../JavaScriptCore/inspector -I ../JavaScriptCore/jit -I ../JavaScriptCore/llint -I ../JavaScriptCore/parser -I ../JavaScriptCore/profiler -I ../JavaScriptCore/runtime -I ../JavaScriptCore/yarr -I ForwardingHeaders -I platform/cairo -I platform/graphics/cairo -I platform/graphics/freetype -I platform/linux -I platform/network/curl -I platform/text/icu  -DENABLE_CANVAS_PATH  -DENABLE_CHANNEL_MESSAGING  -DENABLE_CONTEXT_MENUS  -DENABLE_CSS_BOX_DECORATION_BREAK  -DENABLE_CSS_TRANSFORMS_ANIMATIONS_UNPREFIXED  -DENABLE_DETAILS_ELEMENT  -DENABLE_FTPDIR  -DENABLE_HIDDEN_PAGE_DOM_TIMER_THROTTLING  -DENABLE_ICONDATABASE  -DENABLE_IMAGE_DECODER_DOWN_SAMPLING  -DENABLE_JIT  -DENABLE_LEGACY_VENDOR_PREFIXES  -DENABLE_LINK_PREFETCH  -DENABLE_LLINT  -DENABLE_METER_ELEMENT  -DENABLE_NAVIGATOR_HWCONCURRENCY  -DENABLE_PROMISES  -DENABLE_PROGRESS_ELEMENT  -DENABLE_SVG_FONTS  -DENABLE_TEMPLATE_ELEMENT  -DENABLE_WEB_SOCKETS  -DENABLE_XSLT  -DENABLE_VIEW_MODE_CSS_MEDIA  -DENABLE_CURSOR_SUPPORT  -DENABLE_DRAG_SUPPORT  -DENABLE_FIFTH_VIDEO  -DENABLE_VIDEO  -DENABLE_VIDEO_TRACK  -DENABLE_MATHML  -DENABLE_TEXT_CARET  -DENABLE_TEXT_SELECTION  -DENABLE_WILL_REVEAL_EDGE_EVENTS  -DUSE_TEXTURE_MAPPER  -DENABLE_REQUEST_AUTOCOMPLETE  -DUSE_CROSS_PLATFORM_CONTEXT_MENUS -DENABLE_NETSCAPE_PLUGIN_API=0 -DENABLE_DATE_AND_TIME_INPUT_TYPES=0 -ffunction-sections -fdata-sections -fno-rtti -fno-exceptions -Wall -I/usr/local/include -fvisibility-inlines-hidden -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT rendering/shapes/BoxShape.cpp
rendering/shapes/BoxShape.cpp: In function 'WebCore::LayoutUnit WebCore::adjustRadiusForMarginBoxShape(WebCore::LayoutUnit, WebCore::LayoutUnit)':
rendering/shapes/BoxShape.cpp:46:56: error: call of overloaded 'pow(WebCore::LayoutUnit, int)' is ambiguous
         return radius + (margin * (1 + pow(ratio - 1, 3)));
                                                        ^
In file included from /usr/include/features.h:368:0,
                 from /usr/include/c++/6.3.0/armv7l-unknown-linux-gnueabihf/bits/os_defines.h:39,
                 from /usr/include/c++/6.3.0/armv7l-unknown-linux-gnueabihf/bits/c++config.h:507,
                 from /usr/include/c++/6.3.0/new:39,
                 from ../WTF/wtf/FastMalloc.h:24,
                 from ./config.h:75,
                 from rendering/shapes/BoxShape.cpp:30:
/usr/include/bits/mathcalls.h:153:1: note: candidate: double pow(double, double)
 __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
 ^
In file included from platform/graphics/IntPoint.h:30:0,
                 from platform/graphics/FloatSize.h:31,
                 from platform/graphics/FloatPoint.h:30,
                 from platform/graphics/FloatRect.h:30,
                 from platform/graphics/FloatRoundedRect.h:33,
                 from rendering/shapes/BoxShape.h:33,
                 from rendering/shapes/BoxShape.cpp:31:
/usr/include/c++/6.3.0/cmath:415:3: note: candidate: constexpr long double std::pow(long double, long double)
   pow(long double __x, long double __y)
   ^~~
/usr/include/c++/6.3.0/cmath:411:3: note: candidate: constexpr float std::pow(float, float)
   pow(float __x, float __y)
   ^~~
make: *** [Makefile:3549: rendering/shapes/BoxShape.o] Error 1
make: Leaving directory '/mnt/sda8/usr/src/webkitfltk/Source/WebCore'
Command exited with non-zero status 2
real    7h 9m 52s
user    6h 44m 16s
sys     20m 4.31s
`

**Comment by clbr** [comment]
A case of "gcc too recent for this code". It is fixed in upstream webkit, and already reported in #15.
