### ISSUE TITLE
Compilation error: `loader/ResourceLoader.h:101:100: error: ‘std::function’ has not been declared`, `loader/ResourceLoader.h:101:108: error: expected ‘,’ or ‘...’ before ‘<’ token`.

### ISSUE THREAD

**Issue by dreirund** [clbr/webkitfltk#20]
I am trying to compile the current checkout from git. For compilation, I use the recipe from the Arch Linux AUR package webkitfltk (http://aur.archlinux.org/packages/webkitfltk/), compilation commands below. (The issue I report here also applies if I compile the version 0.5.1 which gets downloaded if I directly use mentioned AUR package.)

Here is the issue:

When building WebCore, I get the following error:

    [...]
    g++ -c -o loader/NetscapePlugInStreamLoader.o -g0 -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -fomit-frame-pointer -fpermissive -DNDEBUG -I .. -I . -I ../WTF -std=gnu++11 -DBUILDING_FLTK__ -D_GLIBCXX_USE_SCHED_YIELD -D_GLIBCXX_USE_NANOSLEEP -I/usr/include  -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/libxml2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I Modules/battery -I Modules/airplay -I Modules/encryptedmedia -I Modules/gamepad -I Modules/gamepad/deprecated -I Modules/geolocation -I Modules/indexeddb -I Modules/indieui -I Modules/mediacontrols/ -I Modules/mediasource -I Modules/mediastream -I Modules/navigatorcontentutils -I Modules/notifications -I Modules/plugins -I Modules/proximity -I Modules/quota -I Modules/speech -I Modules/streams -I Modules/vibration -I Modules/webaudio -I Modules/webdatabase -I Modules/websockets -I accessibility -I bindings -I bindings/generic -I bindings/js -I bridge -I bridge/c -I bridge/jsc -I contentextensions -I crypto -I crypto/algorithms -I crypto/keys -I crypto/parameters -I css -I cssjit -I dom -I dom/default -I editing -I fileapi -I history -I html -I html/canvas -I html/forms -I html/parser -I html/shadow -I html/track -I inspector -I loader -I loader/appcache -I loader/archive -I loader/archive/mhtml -I loader/cache -I loader/icon -I mathml -I page -I page/animation -I page/scrolling -I platform -I platform/animation -I platform/audio -I platform/graphics -I platform/graphics/cpu/arm -I platform/graphics/cpu/arm/filters -I platform/graphics/filters -I platform/graphics/filters/texmap -I platform/graphics/harfbuzz -I platform/graphics/harfbuzz/ng -I platform/graphics/opentype -I platform/graphics/texmap -I platform/graphics/transforms -I platform/image-decoders -I platform/image-decoders/bmp -I platform/image-decoders/gif -I platform/image-decoders/ico -I platform/image-decoders/jpeg -I platform/image-decoders/png -I platform/image-decoders/webp -I platform/mediastream -I platform/mock -I platform/mock/mediasource -I platform/network -I platform/sql -I platform/text -I platform/text/icu -I plugins -I rendering -I rendering/line -I rendering/mathml -I rendering/shapes -I rendering/style -I rendering/svg -I replay -I storage -I style -I svg -I svg/animation -I svg/graphics -I svg/graphics/filters -I svg/properties -I websockets -I workers -I xml -I xml/parser -I ../JavaScriptCore -I ../JavaScriptCore/ForwardingHeaders -I ../JavaScriptCore/API -I ../JavaScriptCore/assembler -I ../JavaScriptCore/bytecode -I ../JavaScriptCore/bytecompiler -I ../JavaScriptCore/dfg -I ../JavaScriptCore/disassembler -I ../JavaScriptCore/heap -I ../JavaScriptCore/debugger -I ../JavaScriptCore/interpreter -I ../JavaScriptCore/inspector -I ../JavaScriptCore/jit -I ../JavaScriptCore/llint -I ../JavaScriptCore/parser -I ../JavaScriptCore/profiler -I ../JavaScriptCore/runtime -I ../JavaScriptCore/yarr -I ForwardingHeaders -I platform/cairo -I platform/graphics/cairo -I platform/graphics/freetype -I platform/linux -I platform/network/curl -I platform/text/icu  -DENABLE_CANVAS_PATH  -DENABLE_CHANNEL_MESSAGING  -DENABLE_CONTEXT_MENUS  -DENABLE_CSS_BOX_DECORATION_BREAK  -DENABLE_CSS_TRANSFORMS_ANIMATIONS_UNPREFIXED  -DENABLE_DETAILS_ELEMENT  -DENABLE_FTPDIR  -DENABLE_HIDDEN_PAGE_DOM_TIMER_THROTTLING  -DENABLE_ICONDATABASE  -DENABLE_IMAGE_DECODER_DOWN_SAMPLING  -DENABLE_JIT  -DENABLE_LEGACY_VENDOR_PREFIXES  -DENABLE_LINK_PREFETCH  -DENABLE_LLINT  -DENABLE_METER_ELEMENT  -DENABLE_NAVIGATOR_HWCONCURRENCY  -DENABLE_PROMISES  -DENABLE_PROGRESS_ELEMENT  -DENABLE_SVG_FONTS  -DENABLE_TEMPLATE_ELEMENT  -DENABLE_WEB_SOCKETS  -DENABLE_XSLT  -DENABLE_VIEW_MODE_CSS_MEDIA  -DENABLE_CURSOR_SUPPORT  -DENABLE_DRAG_SUPPORT  -DENABLE_FIFTH_VIDEO  -DENABLE_VIDEO  -DENABLE_VIDEO_TRACK  -DENABLE_MATHML  -DENABLE_TEXT_CARET  -DENABLE_TEXT_SELECTION  -DENABLE_WILL_REVEAL_EDGE_EVENTS  -DUSE_TEXTURE_MAPPER  -DENABLE_REQUEST_AUTOCOMPLETE  -DUSE_CROSS_PLATFORM_CONTEXT_MENUS -DENABLE_NETSCAPE_PLUGIN_API=0 -DENABLE_DATE_AND_TIME_INPUT_TYPES=0 -ffunction-sections -fdata-sections -fno-rtti -fno-exceptions -Wall -I/usr/include/freetype2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fvisibility-inlines-hidden -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT loader/NetscapePlugInStreamLoader.cpp
    which: no fltk-config13 in (/usr/lib/ccache/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:/usr/bin/vendor_perl:/usr/local/sbin:/usr/local/bin:/usr/games:/home/felics/bin:/home/felics/local/bin:/home/felics/sbin:/home/felics/local/sbin)
    In file included from loader/NetscapePlugInStreamLoader.h:32:0,
                     from loader/NetscapePlugInStreamLoader.cpp:30:
    loader/ResourceLoader.h:101:100: error: ‘std::function’ has not been declared
         virtual void willSendRequest(ResourceRequest&&, const ResourceResponse& redirectResponse, std::function<void(ResourceRequest&)> callback);
                                                                                                        ^~~~~~~~
    loader/ResourceLoader.h:101:108: error: expected ‘,’ or ‘...’ before ‘<’ token
         virtual void willSendRequest(ResourceRequest&&, const ResourceResponse& redirectResponse, std::function<void(ResourceRequest&)> callback);
                                                                                                                ^
    make: *** [Makefile:3549: loader/NetscapePlugInStreamLoader.o] Error 1
    make: Leaving directory '/var/abs/local/own/webkitfltk-git/src/webkitfltk/Source/WebCore'

I am not familiar with C/C++, linking and such stuff, and I don't know if it is an upstream issue or a problem with my system.

Can you check if it is an upstream error or, if not, give advice what might be the problem with my setup?

gcc version: 7.1.1 20170630

For building, the following commands are issued:

    CXXFLAGS+=" -DNDEBUG"
    export CXXFLAGS
    make -C Source/bmalloc/bmalloc
    make -C Source/WTF/wtf
    make -C Source/JavaScriptCore gen
    make -C Source/JavaScriptCore
    make -C Source/WebCore
    make -C Source/WebKit/fltk

**Comment by clbr** [comment]
Most likely an incompatibility with the new GCC version. I haven't had time to check gcc 6, not to even talk about gcc 7. Can you use gcc 5?

**Comment by dreirund** [comment]
With gcc5 it works.

**Comment by clbr** [comment]
Git now compiles with gcc 7. If it works reasonably for a few weeks, I'll tag a new release.

**Comment by isopix** [comment]
Nearly two years passed, and there's still no promised release!

**Comment by clbr** [comment]
Life happened. Please use the git version in the meantime.
