### ISSUE TITLE
fltk-config13 and fltk-config: Misleading warning `which: no fltk-config13 in (<PATH>)`, and references to fltk-config13.

### ISSUE THREAD

**Issue by dreirund** [clbr/webkitfltk#21]
In `Source/Makefile.fltk.shared`, there is the line

    FLTKCONFIG = $(shell which fltk-config13 || which fltk-config)

Well, when `fltk-config13` is not there (even if `fltk-config` is there), there are warning messages printed during comilation:

    which: no fltk-config13 in (<PATH>)

This is confusing and makes one to assume that there might be a problem even if there is not.

I would consider to change it to something like

    FLTKCONFIG = $(shell which fltk-config13 2>/dev/null || which fltk-config)

or even better an if-statement.

Also, the file `Source/WebKit/gtk/Makefile` contains the lines

    CXXFLAGS += $(shell fltk-config13 --cxxflags)

and

    LIBS = -lz -pthread -lxslt -lxml2 -ldl -lsqlite3 `icu-config --ldflags` \
            -lharfbuzz -lharfbuzz-icu -lfreetype -lfontconfig -lcairo \
            -lpng -ljpeg -lrt -lcurl -lssl -lcrypto \
            `fltk-config13 --ldflags`

which rely on fltk-config13 beeing present, but it might only be fltk-config be present (as you acknowledge in `Source/Makefile.fltk.shared`). Is this correct, or a mistake?

I have fltk version 1.3.4 installed, Arch Linux package.

**Comment by clbr** [comment]
> Well, when `fltk-config13` is not there (even if `fltk-config` is there), there are warning messages printed during comilation:
> 
>     which: no fltk-config13 in (<PATH>)
> 
> This is confusing and makes one to assume that there might be a problem even if there is not.

The thing is, there is no standard "which" command. My machine's
"which" prints nothing when the program is not found.

> I would consider to change it to something like
> 
>     FLTKCONFIG = $(shell which fltk-config13 2>/dev/null || which fltk-config)

If you send a tested pull request for this redirection, I'll apply it.

> Also, the file `Source/WebKit/gtk/Makefile` contains the lines

The gtk/ dir is not buildable, it's there mainly for reference
purposes. It has been deleted in upstream webkit long ago. Thus the
Makefile is just a remainder from early webkitfltk development.

I keep the WinCE port around for the same purpose. It too has been
deleted upstream, but it's handy to see how different ports achieved
something. And it as well is likely not buildable.

**Comment by dreirund** [comment]
Don't know how to do pull requests. I leave it as it is, I did not do a deep test run; my modification worked for me, but I don't know what might happen on other implementations.
