### ISSUE TITLE
Webcore does not compile on openSUSE 13.2 and gcc

### ISSUE THREAD

**Issue by omnomnymous** [clbr/webkitfltk#9]
openSUSE 13.2 x86_64 
gcc (SUSE Linux) 4.8.3 20140627 [gcc-4_8-branch revision 212064]

    $ make -C Source/WebCore
    . . .
    g++ -c -o platform/fltk/RenderThemeFLTK.o -I .. -I . -I ../WTF -std=gnu++11 -DBUILDING_FLTK__ -D_GLIBCXX_USE_SCHED_YIELD -D_GLIBCXX_USE_NANOSLEEP -I/usr/include  -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng12 -I/usr/include/libxml2 -I/usr/include/harfbuzz  -I Modules/battery -I Modules/encryptedmedia -I Modules/gamepad -I Modules/geolocation -I Modules/indexeddb -I Modules/indexeddb/leveldb -I Modules/indieui -I Modules/mediacontrols/ -I Modules/mediasource -I Modules/mediastream -I Modules/navigatorcontentutils -I Modules/notifications -I Modules/plugins -I Modules/proximity -I Modules/quota -I Modules/vibration -I Modules/webaudio -I Modules/webdatabase -I Modules/websockets -I accessibility -I bindings -I bindings/generic -I bindings/js -I bridge -I bridge/c -I bridge/jsc -I crypto -I crypto/keys -I css -I cssjit -I dom -I dom/default -I editing -I fileapi -I history -I html -I html/canvas -I html/forms -I html/parser -I html/shadow -I html/track -I inspector -I loader -I loader/appcache -I loader/archive -I loader/archive/mhtml -I loader/cache -I loader/icon -I mathml -I page -I page/animation -I page/scrolling -I platform -I platform/animation -I platform/audio -I platform/graphics -I platform/graphics/cpu/arm -I platform/graphics/cpu/arm/filters -I platform/graphics/filters -I platform/graphics/filters/texmap -I platform/graphics/harfbuzz -I platform/graphics/harfbuzz/ng -I platform/graphics/opentype -I platform/graphics/texmap -I platform/graphics/transforms -I platform/image-decoders -I platform/image-decoders/bmp -I platform/image-decoders/gif -I platform/image-decoders/ico -I platform/image-decoders/jpeg -I platform/image-decoders/png -I platform/image-decoders/webp -I platform/leveldb -I platform/mediastream -I platform/mock -I platform/network -I platform/sql -I platform/text -I platform/text/icu -I plugins -I rendering -I rendering/line -I rendering/mathml -I rendering/shapes -I rendering/style -I rendering/svg -I replay -I storage -I style -I svg -I svg/animation -I svg/graphics -I svg/graphics/filters -I svg/properties -I websockets -I workers -I xml -I xml/parser -I ../JavaScriptCore -I ../JavaScriptCore/ForwardingHeaders -I ../JavaScriptCore/API -I ../JavaScriptCore/assembler -I ../JavaScriptCore/bytecode -I ../JavaScriptCore/bytecompiler -I ../JavaScriptCore/dfg -I ../JavaScriptCore/disassembler -I ../JavaScriptCore/heap -I ../JavaScriptCore/debugger -I ../JavaScriptCore/interpreter -I ../JavaScriptCore/jit -I ../JavaScriptCore/llint -I ../JavaScriptCore/parser -I ../JavaScriptCore/profiler -I ../JavaScriptCore/runtime -I ../JavaScriptCore/yarr -I ForwardingHeaders -I platform/cairo -I platform/graphics/cairo -I platform/graphics/freetype -I platform/linux -I platform/network/curl -I platform/text/icu  -DENABLE_CANVAS_PATH  -DENABLE_CHANNEL_MESSAGING  -DENABLE_CONTEXT_MENUS  -DENABLE_CSS_BOX_DECORATION_BREAK  -DENABLE_CSS_TRANSFORMS_ANIMATIONS_UNPREFIXED  -DENABLE_DETAILS_ELEMENT  -DENABLE_FTPDIR  -DENABLE_HIDDEN_PAGE_DOM_TIMER_THROTTLING  -DENABLE_ICONDATABASE  -DENABLE_IMAGE_DECODER_DOWN_SAMPLING  -DENABLE_INSPECTOR  -DENABLE_JIT  -DENABLE_LEGACY_VENDOR_PREFIXES  -DENABLE_LINK_PREFETCH  -DENABLE_LLINT  -DENABLE_METER_ELEMENT  -DENABLE_NAVIGATOR_HWCONCURRENCY  -DENABLE_PROMISES  -DENABLE_PROGRESS_ELEMENT  -DENABLE_SVG_FONTS  -DENABLE_TEMPLATE_ELEMENT  -DENABLE_WEB_SOCKETS  -DENABLE_XSLT  -DENABLE_SUBPIXEL_LAYOUT  -DENABLE_VIEW_MODE_CSS_MEDIA  -DENABLE_CURSOR_SUPPORT  -DENABLE_DRAG_SUPPORT  -DENABLE_FIFTH_VIDEO  -DENABLE_VIDEO  -DENABLE_VIDEO_TRACK  -DENABLE_MATHML  -DENABLE_TEXT_CARET  -DENABLE_TEXT_SELECTION  -DENABLE_WILL_REVEAL_EDGE_EVENTS  -DWTF_USE_TEXTURE_MAPPER  -DWTF_USE_CROSS_PLATFORM_CONTEXT_MENUS -DENABLE_NETSCAPE_PLUGIN_API=0 -DENABLE_SQL_DATABASE=0 -DENABLE_DATE_AND_TIME_INPUT_TYPES=0 -ffunction-sections -fdata-sections -fno-rtti -fno-exceptions -Wall -I/usr/include/freetype2 -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT platform/fltk/RenderThemeFLTK.cpp
    platform/fltk/RenderThemeFLTK.cpp: In member function ‘bool WebCore::RenderThemeFLTK::paintThemePart(const WebCore::RenderObject&, WebCore::FormType, const WebCore::PaintInfo&, const WebCore::IntRect&)’:
    platform/fltk/RenderThemeFLTK.cpp:143:9: warning: enumeration value ‘FormTypeLast’ not handled in switch [-Wswitch]
      switch (type) {
             ^
    platform/fltk/RenderThemeFLTK.cpp:209:5: error: ‘class Fl_Widget’ has no member named ‘set_active’
      w->set_active();
         ^
    platform/fltk/RenderThemeFLTK.cpp:211:6: error: ‘class Fl_Widget’ has no member named ‘clear_active’
       w->clear_active();
          ^
    platform/fltk/RenderThemeFLTK.cpp:266:19: error: ‘class Fl_Button’ has no member named ‘set_active’
        s_spinnerdown->set_active();
                       ^
    platform/fltk/RenderThemeFLTK.cpp:268:20: error: ‘class Fl_Button’ has no member named ‘clear_active’
         s_spinnerdown->clear_active();
                        ^
    platform/fltk/RenderThemeFLTK.cpp:213:9: warning: enumeration value ‘FormTypeLast’ not handled in switch [-Wswitch]
      switch (type) {
             ^
    Makefile:3468: recipe for target 'platform/fltk/RenderThemeFLTK.o' failed
    make: *** [platform/fltk/RenderThemeFLTK.o] Error 1
    make: Leaving directory '/dev/shm/webkitfltk-0.3/Source/WebCore'
    

How do I compile webkitfltk with musl-gcc?

**Comment by clbr** [comment]
Your FLTK is too old. As mentioned on the website, 1.3.3 or later is
required. If the issue persists after upgrading, please reopen this
issue.

Musl is not supported AFAIK - it will compile but crash at runtime
when executing JS. For the details see the musl ML.

**Comment by omnomnymous** [comment]
After installing FLTK 1.3.3 I was able to build Source/WebCore however building Source/WebKit/fltk fails with error:
    
    g++ -o testapp/testapp testapp/*.cpp -I .. -I ../.. -I . -I ../../WTF -I webkit -I WebCoreSupport -std=gnu++11 -g -Wall -DBUILDING_FLTK__ -D_GLIBCXX_USE_SCHED_YIELD -D_GLIBCXX_USE_NANOSLEEP -I/usr/include  -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng12 -I/usr/include/libxml2 -I/usr/include/harfbuzz  -I ../../JavaScriptCore/ForwardingHeaders -I ../../WebCore -I ../../WebCore/ForwardingHeaders -I ../../WebCore/Modules/geolocation -I ../../WebCore/Modules/filesystem -I ../../WebCore/Modules/mediastream -I ../../WebCore/Modules/navigatorcontentutils -I ../../WebCore/Modules/networkinfo -I ../../WebCore/Modules/webdatabase -I ../../WebCore/Modules/websockets -I ../../WebCore/accessibility -I ../../WebCore/bindings/generic -I ../../WebCore/bindings/js -I ../../WebCore/bindings -I ../../WebCore/bridge -I ../../WebCore/bridge/c -I ../../WebCore/bridge/jsc -I ../../WebCore/css -I ../../WebCore/dom -I ../../WebCore/dom/default -I ../../WebCore/editing -I ../../WebCore/fileapi -I ../../WebCore/history -I ../../WebCore/html -I ../../WebCore/html/forms -I ../../WebCore/html/shadow -I ../../WebCore/inspector -I ../../WebCore/loader -I ../../WebCore/loader/archive -I ../../WebCore/loader/appcache -I ../../WebCore/loader/icon -I ../../WebCore/loader/cache -I ../../WebCore/page -I ../../WebCore/page/animation -I ../../WebCore/page/scrolling -I ../../WebCore/platform -I ../../WebCore/platform/animation -I ../../WebCore/platform/audio -I ../../WebCore/platform/fltk -I ../../WebCore/platform/cairo -I ../../WebCore/platform/graphics -I ../../WebCore/platform/graphics/filters -I ../../WebCore/platform/graphics/harfbuzz -I ../../WebCore/platform/graphics/harfbuzz/ng -I ../../WebCore/platform/graphics/cairo -I ../../WebCore/platform/graphics/texmap -I ../../WebCore/platform/graphics/opentype -I ../../WebCore/platform/graphics/transforms -I ../../WebCore/platform/mediastream -I ../../WebCore/platform/mock -I ../../WebCore/platform/network -I ../../WebCore/platform/network/curl -I ../../WebCore/platform/sql -I ../../WebCore/platform/text -I ../../WebCore/plugins -I ../../WebCore/rendering -I ../../WebCore/rendering/line -I ../../WebCore/rendering/shapes -I ../../WebCore/rendering/style -I ../../WebCore/storage -I ../../WebCore/style -I ../../WebCore/svg -I ../../WebCore/svg/animation -I ../../WebCore/svg/graphics -I ../../WebCore/svg/properties -I ../../WebCore/workers -I ../../JavaScriptCore -I ../../JavaScriptCore/API -I ../../JavaScriptCore/assembler -I ../../JavaScriptCore/bytecode -I ../../JavaScriptCore/bytecompiler -I ../../JavaScriptCore/disassembler -I ../../JavaScriptCore/dfg -I ../../JavaScriptCore/heap -I ../../JavaScriptCore/debugger -I ../../JavaScriptCore/interpreter -I ../../JavaScriptCore/jit -I ../../JavaScriptCore/llint -I ../../JavaScriptCore/parser -I ../../JavaScriptCore/profiler -I ../../JavaScriptCore/runtime  -DENABLE_CANVAS_PATH  -DENABLE_CHANNEL_MESSAGING  -DENABLE_CONTEXT_MENUS  -DENABLE_CSS_BOX_DECORATION_BREAK  -DENABLE_CSS_TRANSFORMS_ANIMATIONS_UNPREFIXED  -DENABLE_DETAILS_ELEMENT  -DENABLE_FTPDIR  -DENABLE_HIDDEN_PAGE_DOM_TIMER_THROTTLING  -DENABLE_ICONDATABASE  -DENABLE_IMAGE_DECODER_DOWN_SAMPLING  -DENABLE_INSPECTOR  -DENABLE_JIT  -DENABLE_LEGACY_VENDOR_PREFIXES  -DENABLE_LINK_PREFETCH  -DENABLE_LLINT  -DENABLE_METER_ELEMENT  -DENABLE_NAVIGATOR_HWCONCURRENCY  -DENABLE_PROMISES  -DENABLE_PROGRESS_ELEMENT  -DENABLE_SVG_FONTS  -DENABLE_TEMPLATE_ELEMENT  -DENABLE_WEB_SOCKETS  -DENABLE_XSLT  -DENABLE_SUBPIXEL_LAYOUT  -DENABLE_VIEW_MODE_CSS_MEDIA  -DENABLE_CURSOR_SUPPORT  -DENABLE_DRAG_SUPPORT  -DENABLE_FIFTH_VIDEO  -DENABLE_VIDEO  -DENABLE_VIDEO_TRACK  -DENABLE_MATHML  -DENABLE_TEXT_CARET  -DENABLE_TEXT_SELECTION  -DENABLE_WILL_REVEAL_EDGE_EVENTS  -DWTF_USE_TEXTURE_MAPPER  -DWTF_USE_CROSS_PLATFORM_CONTEXT_MENUS -DENABLE_NETSCAPE_PLUGIN_API=0 -DENABLE_SQL_DATABASE=0 -DENABLE_DATE_AND_TIME_INPUT_TYPES=0 -DNDEBUG -ffunction-sections -fdata-sections -fno-rtti -fno-exceptions -Wall -I/usr/include/freetype2 -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fvisibility-inlines-hidden -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT /tmp/libwebkitfltk.a \
            -lz -pthread -lxslt -lxml2 -ldl -lsqlite3 `icu-config --ldflags` -lharfbuzz -lharfbuzz-icu -lfreetype -lfontconfig -lcairo -lpng -ljpeg -lrt -lcurl -lssl -lcrypto -lglib-2.0 `/usr/bin/fltk-config --ldflags --use-images` -static-libgcc -static-libstdc++
    /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld:/tmp/libwebkitfltk.a: file format not recognized; treating as linker script
    /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld:/tmp/libwebkitfltk.a:1: syntax error
    collect2: error: ld returned 1 exit status
    Makefile:132: recipe for target 'testapp/testapp' failed
    make: *** [testapp/testapp] Error 1
    make: Leaving directory '/dev/shm/webkitfltk-0.3/Source/WebKit/fltk'
    

    /dev/shm/webkitfltk-0.3 $ file /tmp/libwebkitfltk.a
    /tmp/libwebkitfltk.a: current ar archive

**Comment by clbr** [comment]
Is its size correct (at least 100mb), and does running "ar t /tmp/libwebkitfltk.a" produce correct output?

**Comment by clbr** [comment]
Oh, please make sure there is enough free space on both the build partition and /tmp.

**Comment by omnomnymous** [comment]
Yes the problem was in the free space. I have /dev/shm and /tmp the same ramdisk with the size of 12G and it seems not enough. Will add 2 more GBs and recompile.

**Comment by omnomnymous** [comment]
Update: 14 GB ramdisk is not enough to build. 
Is there any way to make smaller size builds? I've added -NDEBUG to all Makefiles already. 

I don't want to build on hard disk because it's SSD and building big projects make severe impact on disk lifespan.

**Comment by clbr** [comment]
As mentioned in the readme, 1gb is enough for the smallest configuration
 (no -g, -DNDEBUG). My tree in such a config is 791mb, then about 150mb
more are needed for temp files, etc.

Perhaps you have -g somewhere, or a typo in -DNDEBUG?

**Comment by omnomnymous** [comment]
No I have no -g anywhere and afair i used exactly -DNDEBUG (copypasted from readme). But I really made a typo in a post above.

Could you please upload somewhere your makefiles for the smalles configuration?

**Comment by clbr** [comment]
This is the config I use:

export CXXFLAGS="-O3 -march=nocona -pipe -fomit-frame-pointer -DNDEBUG"
make -C ... # normal steps

**Comment by omnomnymous** [comment]
I could not build the Source/WebCore even with 31G /dev/shm - getting the error "ar: libwebcore.a: File truncated". I use your export flags. Any suggestions? 

```
21:41:14 /dev/shm/webkitfltk-0.5.1> df -h .
Filesystem      Size  Used Avail Use% Mounted on
tmpfs            31G   11G   21G  33% /dev/shm

21:41:21 /dev/shm/webkitfltk-0.5.1> cat Source/WebCore/libwebcore.a
!<arch>
```

**Comment by clbr** [comment]
Something is wrong in your setup - my release libwebcore.a is 1.2gb. If you watch the compiles go on, are the flags on the g++ line(s)?

**Comment by omnomnymous** [comment]
Yes, they are.

```
g++ -c -o JSVideoTrackList.o -O3 -march=nocona -pipe -fomit-frame-pointer -DNDEBUG -I .. -I . -I ../WTF -std=gnu++11 -DBUILDING_FLTK__ -D_GLIBCXX_USE_SCHED_YIELD -D_GLIBCXX_USE_NANOSLEEP -I/usr/include  -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/libxml2 -I/usr/include/harfbuzz  -I Modules/battery -I Modules/airplay -I Modules/encryptedmedia -I Modules/gamepad -I Modules/gamepad/deprecated -I Modules/geolocation -I Modules/indexeddb -I Modules/indieui -I Modules/mediacontrols/ -I Modules/mediasource -I Modules/mediastream -I Modules/navigatorcontentutils -I Modules/notifications -I Modules/plugins -I Modules/proximity -I Modules/quota -I Modules/speech -I Modules/streams -I Modules/vibration -I Modules/webaudio -I Modules/webdatabase -I Modules/websockets -I accessibility -I bindings -I bindings/generic -I bindings/js -I bridge -I bridge/c -I bridge/jsc -I contentextensions -I crypto -I crypto/algorithms -I crypto/keys -I crypto/parameters -I css -I cssjit -I dom -I dom/default -I editing -I fileapi -I history -I html -I html/canvas -I html/forms -I html/parser -I html/shadow -I html/track -I inspector -I loader -I loader/appcache -I loader/archive -I loader/archive/mhtml -I loader/cache -I loader/icon -I mathml -I page -I page/animation -I page/scrolling -I platform -I platform/animation -I platform/audio -I platform/graphics -I platform/graphics/cpu/arm -I platform/graphics/cpu/arm/filters -I platform/graphics/filters -I platform/graphics/filters/texmap -I platform/graphics/harfbuzz -I platform/graphics/harfbuzz/ng -I platform/graphics/opentype -I platform/graphics/texmap -I platform/graphics/transforms -I platform/image-decoders -I platform/image-decoders/bmp -I platform/image-decoders/gif -I platform/image-decoders/ico -I platform/image-decoders/jpeg -I platform/image-decoders/png -I platform/image-decoders/webp -I platform/mediastream -I platform/mock -I platform/mock/mediasource -I platform/network -I platform/sql -I platform/text -I platform/text/icu -I plugins -I rendering -I rendering/line -I rendering/mathml -I rendering/shapes -I rendering/style -I rendering/svg -I replay -I storage -I style -I svg -I svg/animation -I svg/graphics -I svg/graphics/filters -I svg/properties -I websockets -I workers -I xml -I xml/parser -I ../JavaScriptCore -I ../JavaScriptCore/ForwardingHeaders -I ../JavaScriptCore/API -I ../JavaScriptCore/assembler -I ../JavaScriptCore/bytecode -I ../JavaScriptCore/bytecompiler -I ../JavaScriptCore/dfg -I ../JavaScriptCore/disassembler -I ../JavaScriptCore/heap -I ../JavaScriptCore/debugger -I ../JavaScriptCore/interpreter -I ../JavaScriptCore/inspector -I ../JavaScriptCore/jit -I ../JavaScriptCore/llint -I ../JavaScriptCore/parser -I ../JavaScriptCore/profiler -I ../JavaScriptCore/runtime -I ../JavaScriptCore/yarr -I ForwardingHeaders -I platform/cairo -I platform/graphics/cairo -I platform/graphics/freetype -I platform/linux -I platform/network/curl -I platform/text/icu  -DENABLE_CANVAS_PATH  -DENABLE_CHANNEL_MESSAGING  -DENABLE_CONTEXT_MENUS  -DENABLE_CSS_BOX_DECORATION_BREAK  -DENABLE_CSS_TRANSFORMS_ANIMATIONS_UNPREFIXED  -DENABLE_DETAILS_ELEMENT  -DENABLE_FTPDIR  -DENABLE_HIDDEN_PAGE_DOM_TIMER_THROTTLING  -DENABLE_ICONDATABASE  -DENABLE_IMAGE_DECODER_DOWN_SAMPLING  -DENABLE_JIT  -DENABLE_LEGACY_VENDOR_PREFIXES  -DENABLE_LINK_PREFETCH  -DENABLE_LLINT  -DENABLE_METER_ELEMENT  -DENABLE_NAVIGATOR_HWCONCURRENCY  -DENABLE_PROMISES  -DENABLE_PROGRESS_ELEMENT  -DENABLE_SVG_FONTS  -DENABLE_TEMPLATE_ELEMENT  -DENABLE_WEB_SOCKETS  -DENABLE_XSLT  -DENABLE_VIEW_MODE_CSS_MEDIA  -DENABLE_CURSOR_SUPPORT  -DENABLE_DRAG_SUPPORT  -DENABLE_FIFTH_VIDEO  -DENABLE_VIDEO  -DENABLE_VIDEO_TRACK  -DENABLE_MATHML  -DENABLE_TEXT_CARET  -DENABLE_TEXT_SELECTION  -DENABLE_WILL_REVEAL_EDGE_EVENTS  -DUSE_TEXTURE_MAPPER  -DENABLE_REQUEST_AUTOCOMPLETE  -DUSE_CROSS_PLATFORM_CONTEXT_MENUS -DENABLE_NETSCAPE_PLUGIN_API=0 -DENABLE_DATE_AND_TIME_INPUT_TYPES=0 -ffunction-sections -fdata-sections -fno-rtti -fno-exceptions -Wall -I/usr/include/freetype2 -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -fvisibility-inlines-hidden -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT JSVideoTrackList.cpp
```

Full build log (zipped 13 megabytes in base64): 

```
curl https://gist.githubusercontent.com/omnomnymous/12eda8e903df9fef30abc3d27a59395a/raw/7e3e0c00936a69522f810d0213169fa5ddfaea6c/log.zip_in_base64.txt -o log.zip_in_base64.txt;
base64 -d log.zip_in_base64.txt > log.zip;
unzip log.zip;
```

Its strange that current build used only 9.4GB instead of 11GB as yesterday.

**Comment by clbr** [comment]
You still have -g in your flags? That will require tons of space. If
you don't need a debug build, find where the -g came from and remove it.

Google tells me some ar versions have trouble with >4gb libraries:
https://sourceware.org/bugzilla/show_bug.cgi?id=14625

So if you do need debug, first try updating your binutils. If that
doesn't help, you can strip the webcore objects to reduce their size,
but that then works against your debug build goal.

Stripping: in WebCore/, run
find -type f | xargs strip -g

**Comment by clbr** [comment]
Sorry, that command should be

find -type f -name "*.o" | xargs strip -g

**Comment by omnomnymous** [comment]
I found -g in ./Source/WebKit/fltk/Makefile line 7:
    `CXXFLAGS += -std=gnu++11 -g -Wall`
I removed it but there is still "...  -O2 -g -m64 ..." in build log, will try to find where it loads from.

Also I noticed there is an extra -O2 option which i haven't found it in Makefiles. I think it is not bad to mix -O3 with -O2, is it?

**Comment by clbr** [comment]
> I found -g in ./Source/WebKit/fltk/Makefile line 7:
>     `CXXFLAGS += -std=gnu++11 -g -Wall`

That only concerns the very small part in that dir, a couple hundred kb
at most.

> I removed it but there is still "...  -O2 -g -m64 ..." in build log, will try to find where it loads from.

fltk-config would be one guess. If not that, it's likely from the gcc
specs, and in that case you should complain to your distro.

> Also I noticed there is an extra -O2 option which i haven't found it in Makefiles. I think it is not bad to mix -O3 with -O2, is it?

The last option is chosen IIRC.

**Comment by omnomnymous** [comment]
You are right, it comes from fltk-config!

```
09:52:39 /dev/shm> fltk-config --cxxflags
-I/usr/include/freetype2 -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -fvisibility-inlines-hidden -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT
```

And fltk-config gets it from opensuse's rpmbuild default settings 

```
optflags: x86_64 -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables
```

I did not find how to override that setting in rpmbuild so I made a dirty hack - removed '-g' option from /usr/lib/rpm/rpmrc and rebuilt the fltk package.

**Comment by omnomnymous** [comment]
I got an error `undefined reference to symbol 'XConvertSelection'` so I had to 
`export CXXFLAGS="-O3 -march=nocona -pipe -fomit-frame-pointer -DNDEBUG -lXrandr -lGL -lGLU -lX11 -lXxf86vm -lXi"`
And now webkitfltk built correctly. Going to build fifth...

**Comment by clbr** [comment]
Isn't -lX11 present in `fltk-config --ldflags --use-images`? It is in mine.

**Comment by omnomnymous** [comment]
Nope

```
13:49:09 /dev/shm> fltk-config --ldflags --use-images
-L/usr/lib64 -lfltk_images -lpng -lz -ljpeg -lfltk
```

**Comment by clbr** [comment]
It definitely should. I wonder if opensuse has a patch for removing
them for some reason, I couldn't find any online resource, just a srpm
which I have no tools to open.

Mine says
`-lfltk_images -lpng -lz -ljpeg -lfltk -lXcursor -lXfixes -lXext -lXft
-lfontconfig -lXinerama -lpthread -ldl -lm -lX11`

You might want to file bugs against opensuse's fltk, this is the second
broken thing (fltk-config's --cxxflags should NOT include -g, or any -O
option).

**Comment by clbr** [comment]
I found a link showing the patches online. Indeed, opensuse applies a patch that removes the libs from fltk-config, which breaks apps. Please open a bug.
